sudo: false
language: php

php:
  - hhvm
  - 5.6
  - 5.5
  - 5.4
  - 5.3

before_script:
  - git clone --depth=50 --branch=master git://github.com/aimeos/arcavias-core.git ../arcavias-core
  - cd ../arcavias-core
  - mv ../ai-symfony2 ext/
  - composer require "symfony/symfony" "2.*"

script:
  - vendor/bin/phing -Ddir=ext/ai-symfony2 coverageext checkext

after_success:
  - php vendor/bin/coveralls -c ext/ai-symfony2/.coveralls.yml