sudo: false
dist: xenial
language: php

services:
  - mysql

php:
  - 7.3
  - 7.2
  - 7.1

env:
  - SYMFONY_VERSION=4.2.*
  - SYMFONY_VERSION=4.1.*
  - SYMFONY_VERSION=4.0.*
  - SYMFONY_VERSION=3.4.*

matrix:
  fast_finish: true
  include:
    - php: 7.0
      env: SYMFONY_VERSION=3.4.*
    - php: 5.6
      env: SYMFONY_VERSION=3.4.*

before_script:
  - git clone --depth=50 --branch=2019.10 git://github.com/aimeos/aimeos-core.git ../aimeos-core
  - cd ../aimeos-core && mv ../ai-symfony ext/
  - if [[ $TRAVIS_PHP_VERSION != "hhvm" ]]; then echo 'memory_limit = -1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi
  - travis_retry composer require "symfony/symfony:${SYMFONY_VERSION}" "zendframework/zend-diactoros:~1.0"
  - mysql -e "CREATE DATABASE aimeos; GRANT ALL ON aimeos.* TO 'aimeos'@'127.0.0.1' IDENTIFIED BY 'aimeos'"
  - echo "<?php return array( 'db' => array( 'adapter' => 'mysql', 'host' => '127.0.0.1', 'database' => 'aimeos', 'username' => 'aimeos', 'password' => 'aimeos', 'limit' => 2, 'opt-persistent' => false, 'stmt' => array( \"SET SESSIOn sort_buffer_size=2097144; SET NAMES 'utf8'; SET SESSION sql_mode='ANSI'\" ) ), 'mq' => array( 'adapter' => 'Standard', 'db' => 'db' ) );" > config/resource.php

script:
  - vendor/bin/phing -Ddir=ext/ai-symfony setup coverageext checkext

after_success:
  - php vendor/bin/coveralls -c ext/ai-symfony/.coveralls.yml
